# Base image: Node.js environment
FROM node:20-alpine

# Set working directory inside container
WORKDIR /app

# Copy package files first (important for caching)
COPY package*.json ./

# Install dependencies
RUN npm install

#  Copy rest of the code
COPY . .

# Expose ports (HTTP + WS)
EXPOSE 3000
EXPOSE 8080

#  Start backend
CMD ["npm", "run", "dev"]